<!DOCTYPE html><html lang='en'><head><title>[except.throw]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>18</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>18.1</a> Throwing an exception <a class='abbr_ref'>[except.throw]</a></h2><p ><span class='indexparent'><a class='index' id=':exception_handling,throwing'></a></span></p><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L193'>#</a></div><p >Throwing an exception transfers control to a handler.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span> 
An exception can be thrown from one of the following contexts:
<i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i><span class='textit'>s</span>,
<a href='basic.stc.dynamic.allocation'>allocation functions</a>,
<a href='expr.dynamic.cast'><span class='texttt'>dynamic_&shy;cast</span></a>,
<a href='expr.typeid'><span class='texttt'>typeid</span></a>,
<i ><a href='expr.new#nt:new-expression'>new-expression</a></i><span class='textit'>s</span>, and standard library
functions (<a href='structure.specifications'>[structure.specifications]</a>).
<span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] 
An object is passed and the type of that object determines which handlers
can catch it.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Example:</span> 
</p><pre class='codeblock'>
throw "Help!";</pre><p >can be caught by a
<i ><a href='except#nt:handler'>handler</a></i>
of
<span class='texttt'>const</span>
<span class='texttt'>char*</span>
type:
</p><pre class='codeblock'>
try {
    <span class='comment'>// ...
</span>}
catch(const char* p) {
    <span class='comment'>// handle character string exceptions here
</span>}</pre><p >and
</p><pre class='codeblock'>
class Overflow {
public:
    Overflow(char,double,double);
};

void f(double x) {
    throw Overflow('+',x,3.45e107);
}</pre><p >can be caught by a handler for exceptions of type
<span class='texttt'>Overflow</span>
</p><pre class='codeblock'>
try {
    f(1.2);
} catch(Overflow&amp; oo) {
    <span class='comment'>// handle exceptions of type <span class='tcode_in_codeblock'>Overflow</span> here
</span>}</pre><p ><span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end example</span><span style='white-space:nowrap'>&thinsp;</span>] </p></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L246'>#</a></div><p ><span class='indexparent'><a class='index' id=':exception_handling,throwing_'></a></span><span class='indexparent'><a class='index' id=':exception_handling,handler'></a></span><span class='indexparent'><a class='index' id=':exception_handling,nearest_handler'></a></span>When an exception is thrown, control is transferred to the nearest handler with
a matching type (<a href='except.handle'>[except.handle]</a>); “nearest” means the handler
for which the
<i ><a href='stmt.block#nt:compound-statement'>compound-statement</a></i> or
<i ><a href='class.base.init#nt:ctor-initializer'>ctor-initializer</a></i>
following the
<span class='texttt'>try</span>
keyword was most recently entered by the thread of control and not yet exited.</p></div><div class='para' id='3'><div class='marginalizedparent'><a class='marginalized' href='#3'>3</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L259'>#</a></div><p >Throwing an exception
copy-initializes (<a href='dcl.init'>[dcl.init]</a>, <a href='class.copy'>[class.copy]</a>) a temporary object,
called the
<a class='hidden_link' href='#def:exception_handling,exception_object' id='def:exception_handling,exception_object'><i >exception object</i></a>.
An lvalue denoting the temporary is used to initialize the
variable declared in the matching
<i ><a href='except#nt:handler'>handler</a></i> (<a href='except.handle'>[except.handle]</a>).
If the type of the exception object would
be an incomplete type or a pointer to an incomplete
type other than <span class='textit'>cv</span> <span class='texttt'>void</span> the program is ill-formed.</p></div><div class='para' id='4'><div class='marginalizedparent'><a class='marginalized' href='#4'>4</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L271'>#</a></div><p ><span class='indexparent'><a class='index' id=':exception_handling,memory'></a></span><span class='indexparent'><a class='index' id=':exception_handling,rethrowing'></a></span><span class='indexparent'><a class='index' id=':exception_handling,exception_object'></a></span>The memory for the exception object is
allocated in an unspecified way, except as noted in <a href='basic.stc.dynamic.allocation'>[basic.stc.dynamic.allocation]</a>.
If a handler exits by rethrowing, control is passed to another handler for
the same exception object.
The points of potential destruction for the exception object are:</p><ul class='itemize'><li id='4.1'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#4.1'>(4.1)</a></div><p >when an active handler for the exception exits by
any means other than
rethrowing,
immediately after the destruction of the object (if any)
declared in the <i ><a href='except#nt:exception-declaration'>exception-declaration</a></i> in the handler;</p></li><li id='4.2'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#4.2'>(4.2)</a></div><p >when an object of type <a href='propagation#lib:exception_ptr'><span class='texttt'>std&#x200b;::&#x200b;exception_&shy;ptr</span></a>
that refers to the exception object is destroyed,
before the destructor of <span class='texttt'>std&#x200b;::&#x200b;exception_&shy;ptr</span> returns.
</p></li></ul><p >Among all points of potential destruction for the exception object,
there is an unspecified last one
where the exception object is destroyed.
All other points <a href='intro.races#def:happens_before'>happen before</a> that last one.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span> 
No other thread synchronization is implied in exception handling.
<span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] 
The implementation may then
deallocate the memory for the exception object; any such deallocation
is done in an unspecified way.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span>  A thrown exception does not
propagate to other threads unless caught, stored, and rethrown using
appropriate library functions; see <a href='propagation'>[propagation]</a> and <a href='futures'>[futures]</a>. <span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] </p></div><div class='para' id='5'><div class='marginalizedparent'><a class='marginalized' href='#5'>5</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L309'>#</a></div><p ><span class='indexparent'><a class='index' id=':exception_handling,exception_object,constructor'></a></span><span class='indexparent'><a class='index' id=':exception_handling,exception_object,destructor'></a></span>When the thrown object is a class object, the constructor selected for
the copy-initialization as well as the constructor selected for
a copy-initialization considering the thrown object as an lvalue
shall be non-deleted and accessible, even if the copy/move operation is
<a href='class.copy.elision'>elided</a>.
The destructor is <a href='class.dtor#def:potentially_invoked'>potentially invoked</a>.</p></div><div class='para' id='6'><div class='marginalizedparent'><a class='marginalized' href='#6'>6</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L319'>#</a></div><p ><span class='indexparent'><a class='index' id=':exception_handling,rethrow'></a></span>An exception is considered caught when a handler for that exception
becomes <a href='except.handle#def:exception_handling,handler,active'>active</a>.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span> 
An exception can have active handlers and still be considered uncaught if
it is rethrown.
<span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] </p></div><div class='para' id='7'><div class='marginalizedparent'><a class='marginalized' href='#7'>7</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/4ad1c6bb8e53bd32bd475d8b199e5ce01b8556f1/source/exceptions.tex#L329'>#</a></div><p ><span class='indexparent'><a class='index' id=':exception_handling,terminate_called'></a></span><span class='indexparent'><a class='index' id=':terminate,called'></a></span>If the exception handling mechanism
handling an <a href='except.uncaught'>uncaught exception</a>
directly invokes a function that exits via an
exception, <a href='except.terminate'><span class='texttt'>std&#x200b;::&#x200b;terminate</span></a> is called.
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Example:</span> 
</p><pre class='codeblock'>
struct C {
  C() { }
  C(const C&amp;) {
    if (std::uncaught_exceptions()) {
      throw 0;      <span class='comment'>// throw during copy to handler's <i ><a href='except#nt:exception-declaration'>exception-declaration</a></i> object (<a href='except.handle'>[except.handle]</a>)
</span>    }
  }
};

int main() {
  try {
    throw C();      <span class='comment'>// calls <span class='tcode_in_codeblock'>std&#x200b;::&#x200b;terminate()</span> if construction of the handler's
</span>                    <span class='comment'>// <i ><a href='except#nt:exception-declaration'>exception-declaration</a></i> object is not <a href='class.copy.elision'>elided</a>
</span>  } catch(C) { }
}</pre><p ><span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end example</span><span style='white-space:nowrap'>&thinsp;</span>] 
[<span style='white-space:nowrap'>&thinsp;</span><span class='textit'>Note:</span> 
Consequently, destructors should generally catch exceptions and not let them propagate.
<span class='textit'><span style='white-space:nowrap'>&thinsp;</span>—<span style='white-space:nowrap'>&thinsp;</span>end note</span><span style='white-space:nowrap'>&thinsp;</span>] </p></div></div></body></html>