<!DOCTYPE html><html lang='en'><head><title>[except.unexpected]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>15</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>15.5</a> Special functions <a class='abbr_ref' href='except.special#except.unexpected'>[except.special]</a></h2><div id='except.unexpected'><h3 ><a class='secnum' style='min-width:103pt'>15.5.2</a> The <span class='texttt'>std::unexpected()</span> function <a class='abbr_ref'>[except.unexpected]</a></h3><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><p ><span class='indexparent'><a class='index' id='unexpected()'></a></span>If a function with
a <i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
exits via an exception
of a type that is not allowed by its exception specification,
the function
<span class='texttt'>std::unexpected()</span>
is called (<a href='exception.unexpected'>[exception.unexpected]</a>) immediately after completing
the stack unwinding for the former function.</p></div><div class='para' id='2'><div class='marginalizedparent'><a class='marginalized' href='#2'>2</a></div><p >[&nbsp;<i>Note:</i><span class='space'></span> By default, <span class='texttt'>std::unexpected()</span> calls <span class='texttt'>std::terminate()</span>, but a
program can install its own handler function (<a href='set.unexpected'>[set.unexpected]</a>). In either case, the
constraints in the following paragraph apply. <i>&nbsp;—&nbsp;end note</i>&nbsp;]</p></div><div class='para' id='3'><div class='marginalizedparent'><a class='marginalized' href='#3'>3</a></div><p >The
<span class='texttt'>std::unexpected()</span>
function shall not return, but it can throw (or rethrow) an exception.
If it throws a new exception which is allowed by the exception specification
which previously was violated, then the search for another handler
will continue at the call of the function whose exception specification was violated.
If it exits via an exception of a type that the
<i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
does not allow,
then the following happens:
<span class='indexparent'><a class='index' id='bad_exception'></a></span>If the
<i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
does not include the class
<span class='texttt'>std::bad_exception</span> (<a href='bad.exception'>[bad.exception]</a>)
then the function
<span class='texttt'>std::terminate()</span>
is called, otherwise the thrown exception is replaced by an
implementation-defined object of type
<span class='texttt'>std::bad_exception</span>
and the search for another handler will continue at the call of the function
whose
<i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
was violated.</p></div><div class='para' id='4'><div class='marginalizedparent'><a class='marginalized' href='#4'>4</a></div><p >[&nbsp;<i>Note:</i><span class='space'></span>
Thus,
a <i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
guarantees that a function exits only via an exception of one of the listed types.
If the
<i ><a href='except.spec#dynamic-exception-specification'>dynamic-exception-specification</a></i>
includes the type
<span class='texttt'>std::bad_exception</span>
then any exception type not on the list may be replaced by
<span class='texttt'>std::bad_exception</span>
within the function
<span class='texttt'>std::unexpected()</span>.
<i>&nbsp;—&nbsp;end note</i>&nbsp;]</p></div></div></div></body></html>