<!DOCTYPE html><html lang='en'><head><title>[except.special]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>15</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><div id='except.special'><h2 ><a class='secnum' style='min-width:88pt'>15.5</a> Special functions <a class='abbr_ref'>[except.special]</a></h2><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/08fda7e637d27fa331a8fcfc64db98d52ae3b6fd/source/exceptions.tex#L974'>#</a></div><p >The function <span class='texttt'>std&#x200b;::&#x200b;terminate()</span> (<a href='except.terminate'>[except.terminate]</a>)
is used by the exception
handling mechanism for coping with errors related to the exception handling
mechanism itself. The function
<span class='texttt'>std&#x200b;::&#x200b;current_&shy;exception()</span> (<a href='propagation'>[propagation]</a>) and the class
<span class='texttt'>std&#x200b;::&#x200b;nested_&shy;exception</span> (<a href='except.nested'>[except.nested]</a>) can be used by a program to
capture the currently handled exception.</p></div><div id='except.terminate'><h3 ><a class='secnum' href='#except.terminate' style='min-width:103pt'>15.5.1</a> The <span class='texttt'>std&#x200b;::&#x200b;terminate()</span> function <a class='abbr_ref' href='except.terminate'>[except.terminate]</a></h3><div class='para' id='except.terminate-1'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/08fda7e637d27fa331a8fcfc64db98d52ae3b6fd/source/exceptions.tex#L985'>#</a></div><p ><span class='indexparent'><a class='index' id='terminate'></a></span>In some situations exception handling must be abandoned
for less subtle error handling techniques. [<span style='white-space:nowrap'>&thinsp;</span><i>Note:</i> These situations are:</p><p ><span class='indexparent'><a class='index' id='terminate,called'></a></span></p><ul class='itemize'><li id='except.terminate-1.1'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.1'>(1.1)</a></div><p >when the exception handling mechanism, after completing
the initialization of the exception object
but before
activation of a handler for the exception (<a href='except.throw'>[except.throw]</a>),
calls a function that exits
via an exception, or</p></li><li id='except.terminate-1.2'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.2'>(1.2)</a></div><p >when the exception handling mechanism cannot find a handler for a thrown exception (<a href='except.handle'>[except.handle]</a>), or</p></li><li id='except.terminate-1.3'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.3'>(1.3)</a></div><p >when the search for a handler (<a href='except.handle'>[except.handle]</a>) encounters the
outermost block of a function
with a non-throwing exception specification (<a href='except.spec'>[except.spec]</a>), or</p></li><li id='except.terminate-1.4'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.4'>(1.4)</a></div><p >when the destruction of an object during stack unwinding (<a href='except.ctor'>[except.ctor]</a>)
terminates by throwing an exception, or</p></li><li id='except.terminate-1.5'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.5'>(1.5)</a></div><p >when initialization of a non-local
variable with static or thread storage duration (<a href='basic.start.dynamic'>[basic.start.dynamic]</a>)
exits via an exception, or</p></li><li id='except.terminate-1.6'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.6'>(1.6)</a></div><p >when destruction of an object with static or thread storage duration exits
via an exception (<a href='basic.start.term'>[basic.start.term]</a>), or</p></li><li id='except.terminate-1.7'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.7'>(1.7)</a></div><p >when execution of a function registered with
<span class='texttt'>std&#x200b;::&#x200b;atexit</span> or <span class='texttt'>std&#x200b;::&#x200b;at_&shy;quick_&shy;exit</span>
exits via an exception (<a href='support.start.term'>[support.start.term]</a>), or</p></li><li id='except.terminate-1.8'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.8'>(1.8)</a></div><p >when a
<i ><a href='expr.throw#nt:throw-expression'>throw-expression</a></i> (<a href='expr.throw'>[expr.throw]</a>)
with no operand attempts to rethrow an exception and no exception is being
handled (<a href='except.throw'>[except.throw]</a>), or</p></li><li id='except.terminate-1.9'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.9'>(1.9)</a></div><p >when the function <span class='texttt'>std&#x200b;::&#x200b;nested_&shy;exception&#x200b;::&#x200b;rethrow_&shy;nested</span> is called for an object
that has captured no exception (<a href='except.nested'>[except.nested]</a>), or</p></li><li id='except.terminate-1.10'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.10'>(1.10)</a></div><p >when execution of the initial function of a thread exits via
an exception (<a href='thread.thread.constr'>[thread.thread.constr]</a>), or</p></li><li id='except.terminate-1.11'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.11'>(1.11)</a></div><p >for a parallel algorithm whose <span class='texttt'>ExecutionPolicy</span> specifies such
behavior (<a href='execpol.seq'>[execpol.seq]</a>, <a href='execpol.par'>[execpol.par]</a>, <a href='execpol.parunseq'>[execpol.parunseq]</a>),
when execution of an element access function (<a href='algorithms.parallel.defns'>[algorithms.parallel.defns]</a>)
of the parallel algorithm exits via an exception (<a href='algorithms.parallel.exceptions'>[algorithms.parallel.exceptions]</a>), or</p></li><li id='except.terminate-1.12'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.12'>(1.12)</a></div><p >when the destructor or the copy assignment operator is invoked on an object
of type <span class='texttt'>std&#x200b;::&#x200b;thread</span> that refers to a joinable thread
(<a href='thread.thread.destr'>[thread.thread.destr]</a>, <a href='thread.thread.assign'>[thread.thread.assign]</a>), or</p></li><li id='except.terminate-1.13'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.13'>(1.13)</a></div><p >when a call to a <span class='texttt'>wait()</span>, <span class='texttt'>wait_&shy;until()</span>, or <span class='texttt'>wait_&shy;for()</span>
function on a condition variable (<a href='thread.condition.condvar'>[thread.condition.condvar]</a>, <a href='thread.condition.condvarany'>[thread.condition.condvarany]</a>)
fails to meet a postcondition.</p></li></ul><p ><i><span style='white-space:nowrap'>&thinsp;</span>â€”<span style='white-space:nowrap'>&thinsp;</span>end note</i><span style='white-space:nowrap'>&thinsp;</span>]</p></div><div class='para' id='except.terminate-2'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/08fda7e637d27fa331a8fcfc64db98d52ae3b6fd/source/exceptions.tex#L1059'>#</a></div><p ><span class='indexparent'><a class='index' id='terminate'></a></span>In such cases,
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called (<a href='exception.terminate'>[exception.terminate]</a>).
In the situation where no matching handler is found, it is
<span class='indexparent'><a class='index' id='stack_unwinding_before_call_to_std::terminate()'></a></span>implementation-defined whether or not the
stack is unwound
before
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called.
In the situation where the search for a handler (<a href='except.handle'>[except.handle]</a>) encounters the
outermost block of a function
with a non-throwing exception specification (<a href='except.spec'>[except.spec]</a>), it is
<span class='indexparent'><a class='index' id='whether_stack_is_unwound_before_calling_std::terminate()_when_a_noexcept_specification_is_violated'></a></span>implementation-defined
whether the stack is unwound, unwound partially, or not unwound at all
before <span class='texttt'>std&#x200b;::&#x200b;terminate()</span> is called.
In all other situations, the stack shall not be unwound before
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>
is called.
An implementation is not permitted to finish stack unwinding
prematurely based on a determination that the unwind process
will eventually cause a call to
<span class='texttt'>std&#x200b;::&#x200b;terminate()</span>.</p></div></div><div id='except.uncaught'><h3 ><a class='secnum' href='#except.uncaught' style='min-width:103pt'>15.5.2</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span> function <a class='abbr_ref' href='except.uncaught'>[except.uncaught]</a></h3><p ><span class='indexparent'><a class='index' id='uncaught_exceptions'></a></span></p><div class='para' id='except.uncaught-1'><div class='marginalizedparent'><a class='marginalized' href='#except.uncaught-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/08fda7e637d27fa331a8fcfc64db98d52ae3b6fd/source/exceptions.tex#L1089'>#</a></div><p >An exception is considered uncaught
after completing the initialization of the exception object (<a href='except.throw'>[except.throw]</a>)
until completing the activation of a handler for the exception (<a href='except.handle'>[except.handle]</a>).
This includes stack unwinding.
If an exception is rethrown (<a href='expr.throw'>[expr.throw]</a>, <a href='propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught.
The function <span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span> (<a href='uncaught.exceptions'>[uncaught.exceptions]</a>)
returns the number of uncaught exceptions in the current thread.<span class='indexparent'><a class='index' id='exception_handling'></a></span>
</p></div></div></div></div></body></html>